services:

  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5

  bentopdf:
    container_name: bentopdf
    image: bentopdf/bentopdf:latest
    healthcheck:
      test: wget --spider http://localhost:8080 > /dev/null 2>&1 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  grist:
    container_name: grist
    image: gristlabs/grist:1.7.10
    environment:
        - PORT=9999
        - GRIST_DEFAULT_EMAIL=diegojonathanheer@gmail.com
    volumes:
        - /home/${USERNAME}/services_data/glance/persist:/persist
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/status"]
      interval: 30s
      retries: 3
      timeout: 5s
      start_period: 10s
      start_interval: 5s

  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:2.4.6
    volumes:
      - /home/${USERNAME}/services_data/n8n:/home/node/.n8n
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - TZ=Europe/Amsterdam
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - N8N_HOST=n8n.dynbase.nl
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.dynabase.nl/
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n_postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${N8N_POSTGRES_PASSWORD}
      - DB_POSTGRESDB_SCHEMA=public
    healthcheck:
      test: wget --spider http://localhost:5678/healthz > /dev/null 2>&1 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  n8n_postgres:
    container_name: n8n_postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: ${N8N_POSTGRES_PASSWORD}
      POSTGRES_DB: n8n
    volumes:
      - /home/${USERNAME}/services_data/n8n/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  docuseal:
    container_name: docuseal
    image: docuseal/docuseal:2.3.0
    volumes:
      - /home/${USERNAME}/services_data/docuseal:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  changedetection:
    container_name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io
    restart: unless-stopped
    volumes:
      - /home/${USERNAME}/services_data/changedetection:/datastore

  tandoor:
    container_name: tandoor
    image: vabene1111/recipes:2.3.6
    environment:
      - SECRET_KEY=YOUR_SECRET_KEY
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=tandoor_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangodb
      - POSTGRES_PASSWORD=${TANDOOR_POSTGRES_PASSWORD}
      - POSTGRES_DB=djangodb
    volumes:
      - /home/${USERNAME}/services_data/tandoor/staticfiles:/opt/recipes/staticfiles
      - /home/${USERNAME}/services_data/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - tandoor_postgres

  tandoor_postgres:
    container_name: tandoor_postgres
    restart: unless-stopped
    image: postgres:16-alpine
    volumes:
      - /home/${USERNAME}/services_data/tandoor/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=djangodb
      - POSTGRES_PASSWORD=${TANDOOR_POSTGRES_PASSWORD}
      - POSTGRES_DB=djangodb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U djangodb -d djangodb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  karakeep:
    container_name: karakeep
    image: ghcr.io/karakeep-app/karakeep:0.30.0
    environment:
      NEXTAUTH_SECRET: cT5y27aUbvkIest7LRwYKR5+drA4uZuQ9c4542DKqptNFMju
      MEILI_MASTER_KEY: M2nna4BSVeUcInvUEsJ5AFAdTU8xH5IVoumon1YzJslvw4M+
      NEXTAUTH_URL: https://karakeep.dynabase.nl
      MEILI_ADDR: http://karakeep_meilisearch:7700
      BROWSER_WEB_URL: http://karakeep_chrome:9222
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATA_DIR: /data
    volumes:
      - /home/${USERNAME}/services_data/karakeep/data:/data

  karakeep_chrome:
    container_name: karakeep_chrome
    image: gcr.io/zenika-hub/alpine-chrome:124
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  karakeep_meilisearch:
    container_name: karakeep_meilisearch
    image: getmeili/meilisearch:v1.13.3
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /home/${USERNAME}/services_data/karakeep/meilisearch:/meili_data

  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${USERNAME}/services_data/dockhand:/app/data

  dash:
    container_name: dash
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
    volumes:
      - /:/mnt/host:ro

networks:
  default:
    external: true
    name: home_server_network