services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v8.14.9
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${USERNAME}/services_data/dozzle:/data
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5

  stirling-pdf:
    container_name: stirling-pdf
    image: stirlingtools/stirling-pdf:0.45.6
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/info/status"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 15s

  grist:
    container_name: grist
    image: gristlabs/grist:1.5.1
    environment:
        - PORT=9999
        - GRIST_DEFAULT_EMAIL=diegojonathanheer@gmail.com
        - GRIST_OIDC_IDP_ISSUER=https://pocket-id.dynabase.xyz/.well-known/openid-configuration
        - GRIST_OIDC_IDP_CLIENT_ID=8cfc1029-f371-4455-a1cd-2382bcfb03ab
        - GRIST_OIDC_IDP_CLIENT_SECRET=lTTJxyDmwps8lzoWFQ5gHV3FTYhNg44l
        - GRIST_OIDC_SP_HOST=https://grist.dynabase.xyz
        - GRIST_OIDC_IDP_SCOPES=openid email profile
        - GRIST_OIDC_IDP_SKIP_END_SESSION_ENDPOINT=true
    volumes:
        - /home/${USERNAME}/services_data/glance/persist:/persist
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/status"]
      interval: 30s
      retries: 3
      timeout: 5s
      start_period: 10s
      start_interval: 5s

  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:1.106.3
    volumes:
      - /home/${USERNAME}/services_data/n8n:/home/node/.n8n
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - TZ=Europe/Amsterdam
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - N8N_HOST=n8n.dynbase.xyz
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.dynabase.xyz/
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n_postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${N8N_POSTGRES_PASSWORD}
      - DB_POSTGRESDB_SCHEMA=public
    healthcheck:
      test: wget --spider http://localhost:5678/healthz > /dev/null 2>&1 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  n8n_postgres:
    container_name: n8n_postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: ${N8N_POSTGRES_PASSWORD}
      POSTGRES_DB: n8n
    volumes:
      - /home/${USERNAME}/services_data/n8n/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  zerobyte:
    container_name: zerobyte
    image: ghcr.io/nicotsx/zerobyte:v0.13
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte
      - /home/${USERNAME}/.config/rclone:/root/.config/rclone
      - /media/hd1/nextcloud/${USERNAME}/files:/nextcloud
      - /home/${USERNAME}/services_data:/services_data
      - /media/hd1/photo_library:/photo_library
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4096"]
      interval: 10s
      timeout: 5s
      retries: 5

  docuseal:
    container_name: docuseal
    image: docuseal/docuseal:2.2.2
    volumes:
      - /home/${USERNAME}/services_data/docuseal:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  changedetection:
    container_name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io
    restart: unless-stopped
    volumes:
      - /home/${USERNAME}/services_data/changedetection:/datastore

  tandoor:
    container_name: tandoor
    image: vabene1111/recipes:2.3.5
    environment:
      - SECRET_KEY=YOUR_SECRET_KEY
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=tandoor_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangodb
      - POSTGRES_PASSWORD=${TANDOOR_POSTGRES_PASSWORD}
      - POSTGRES_DB=djangodb
      - SOCIAL_DEFAULT_ACCESS=1
      - SOCIAL_PROVIDERS=allauth.socialaccount.providers.openid_connect
      - SOCIALACCOUNT_PROVIDERS={"openid_connect":{"OAUTH_PKCE_ENABLED":True,"APPS":[{"provider_id":"oidc","name":"PocketID","client_id":"660f5989-ba93-4b2c-83b8-6117b17cb12e","secret":"ei9GJWbjG5APM56ix07JLo4lrimLs9W6","settings":{"fetch_userinfo":True,"oauth_pkce_enabled":True,"server_url":"https://pocket-id.dynabase.xyz/.well-known/openid-configuration"}}]}}
    volumes:
      - /home/${USERNAME}/services_data/tandoor/staticfiles:/opt/recipes/staticfiles
      - /home/${USERNAME}/services_data/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - tandoor_postgres

  tandoor_postgres:
    container_name: tandoor_postgres
    restart: unless-stopped
    image: postgres:16-alpine
    volumes:
      - /home/${USERNAME}/services_data/tandoor/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=djangodb
      - POSTGRES_PASSWORD=${TANDOOR_POSTGRES_PASSWORD}
      - POSTGRES_DB=djangodb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U djangodb -d djangodb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  karakeep:
    container_name: karakeep
    image: ghcr.io/karakeep-app/karakeep:0.28.0
    environment:
      NEXTAUTH_SECRET: cT5y27aUbvkIest7LRwYKR5+drA4uZuQ9c4542DKqptNFMju
      MEILI_MASTER_KEY: M2nna4BSVeUcInvUEsJ5AFAdTU8xH5IVoumon1YzJslvw4M+
      NEXTAUTH_URL: https://karakeep.dynabase.xyz
      MEILI_ADDR: http://karakeep_meilisearch:7700
      BROWSER_WEB_URL: http://karakeep_chrome:9222
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATA_DIR: /data
    volumes:
      - /home/${USERNAME}/services_data/karakeep/data:/data

  karakeep_chrome:
    container_name: karakeep_chrome
    image: gcr.io/zenika-hub/alpine-chrome:124
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  karakeep_meilisearch:
    container_name: karakeep_meilisearch
    image: getmeili/meilisearch:v1.13.3
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /home/${USERNAME}/services_data/karakeep/meilisearch:/meili_data

networks:
  default:
    external: true
    name: home_server_network